//! The web chat: a user's conversations in a guild, with answers streamed as server-sent
//! events. A conversation belongs to its user (another user's is 404). Listing, starting one
//! and sending a message need the right to use the bot in the guild, checked anew every time,
//! so a removed role, a denied guild or one the bot left stops the chat. Answers share /talk's
//! generation limits (one per user, four in all) and run in a task of their own, which ends
//! when the answer is complete, the browser goes away, the user presses stop, the bot shuts down
//! or REQUEST_TIMEOUT_SECONDS pass, and saves what was generated by then.

use std::{
    collections::{HashMap, VecDeque},
    convert::Infallible,
    sync::Mutex,
    time::{Duration, Instant},
};

use axum::{
    Json,
    extract::{Path, Query, State, rejection::QueryRejection},
    http::StatusCode,
    response::sse::{Event, KeepAlive, Sse},
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tokio::sync::{mpsc, watch};
use tokio_stream::{Stream, StreamExt, wrappers::ReceiverStream};

use super::{
    ApiError, AppState, INTERNAL_ERROR, JsonBody, Web,
    auth::Session,
    authz,
    chat_store::{
        ConversationRow, Finished, MAX_TITLE_CHARS, MAX_TURNS_PER_CONVERSATION, MessageRow,
        NewTurn, Posted, Status, context, valid_title,
    },
};
use crate::{
    agent::{AgentError, Answer, ChatRequest, Source, StreamEvent, Turn},
    ids::{id_string, parse_snowflake},
    knowledge::{consult, store::KbSource},
    limits::{Busy, Key, Lease},
};

/// Longest question, as for /talk.
const MAX_QUESTION_CHARS: usize = 4_000;
/// Request body of a message: 4,000 characters of up to 4 bytes, escaped as JSON, fit easily.
pub const MAX_MESSAGE_BODY_BYTES: usize = 64 * 1024;
/// The window of WEB_DAILY_MESSAGES_PER_USER.
const DAY: Duration = Duration::from_secs(86_400);
const KEEP_ALIVE: Duration = Duration::from_secs(15);
/// Events waiting for a slow browser (and for the relay from the agent).
const EVENT_BUFFER: usize = 64;
/// Saving how an answer ended gets this long, shutdown or not; so does telling the browser (one
/// that stops reading must not keep the generation slot).
const SAVE_TIMEOUT: Duration = Duration::from_secs(5);
/// Users whose recent questions are remembered before stale ones are swept.
const RECENT_USERS: usize = 1_000;

const NO_USE_RIGHT: &str =
    "このサーバーでチャットを使う権限がありません（サーバー管理者が許可したロールが必要です）。";
const INTERRUPTED: &str = "Botの再起動などにより回答が中断されました。もう一度送信してください。";
const NOT_SAVED: &str = "回答を保存できませんでした。時間をおいて再試行してください。";

/// What the chat keeps in memory (one process): the answers being generated, so that they can
/// be stopped, and each user's recent questions, so that deleting conversations does not reset
/// the daily limit.
pub struct Chat {
    running: Mutex<HashMap<u64, Running>>,
    shutdown: watch::Sender<bool>,
    recent: Mutex<HashMap<u64, VecDeque<Instant>>>,
}

struct Running {
    conversation: u64,
    answer: u64,
    stop: watch::Sender<bool>,
}

impl Default for Chat {
    fn default() -> Self {
        Self {
            running: Mutex::default(),
            shutdown: watch::channel(false).0,
            recent: Mutex::default(),
        }
    }
}

impl Chat {
    /// Stops the user's answer being generated; false if there is none.
    pub fn stop(&self, user: u64) -> bool {
        let running = self.running.lock().expect("chat lock poisoned");
        running
            .get(&user)
            .is_some_and(|run| run.stop.send(true).is_ok())
    }

    /// Ends every answer being generated, saving what each has (the bot is shutting down).
    pub fn shut_down(&self) {
        self.shutdown.send_replace(true);
    }

    fn stop_conversation(&self, user: u64, conversation: u64) {
        let running = self.running.lock().expect("chat lock poisoned");
        if let Some(run) = running.get(&user)
            && run.conversation == conversation
        {
            let _ = run.stop.send(true);
        }
    }

    /// The ID of the user's answer being generated.
    fn running_answer(&self, user: u64) -> Option<u64> {
        let running = self.running.lock().expect("chat lock poisoned");
        running.get(&user).map(|run| run.answer)
    }

    fn register(&self, user: u64, conversation: u64, answer: u64) -> watch::Receiver<bool> {
        let (stop, stopped) = watch::channel(false);
        let mut running = self.running.lock().expect("chat lock poisoned");
        running.insert(
            user,
            Running {
                conversation,
                answer,
                stop,
            },
        );
        stopped
    }

    fn unregister(&self, user: u64, answer: u64) {
        let mut running = self.running.lock().expect("chat lock poisoned");
        if running.get(&user).is_some_and(|run| run.answer == answer) {
            running.remove(&user);
        }
    }

    /// Questions the user sent in the last 24 hours, as far as this process has seen.
    fn recent_questions(&self, user: u64) -> u32 {
        let mut recent = self.recent.lock().expect("chat lock poisoned");
        let Some(times) = recent.get_mut(&user) else {
            return 0;
        };
        forget_old(times);
        let count = times.len() as u32;
        if times.is_empty() {
            recent.remove(&user);
        }
        count
    }

    fn record_question(&self, user: u64) {
        let mut recent = self.recent.lock().expect("chat lock poisoned");
        if recent.len() >= RECENT_USERS {
            recent.retain(|_, times| {
                forget_old(times);
                !times.is_empty()
            });
        }
        recent.entry(user).or_default().push_back(Instant::now());
    }
}

fn forget_old(times: &mut VecDeque<Instant>) {
    while times.front().is_some_and(|at| at.elapsed() >= DAY) {
        times.pop_front();
    }
}

#[derive(Deserialize)]
pub struct GuildQuery {
    guild: Option<String>,
}

#[derive(Serialize)]
pub struct ConversationList {
    conversations: Vec<ConversationView>,
    /// Whether to offer the knowledge base: it is enabled and the guild has ready documents.
    knowledge: bool,
    daily_limit: u32,
    /// Questions sent in the last 24 hours.
    daily_used: u32,
}

#[derive(Serialize)]
pub struct ConversationView {
    id: u64,
    #[serde(with = "id_string")]
    guild_id: u64,
    /// `null` until the first message names it.
    title: Option<String>,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
}

#[derive(Serialize)]
pub struct ConversationDetail {
    #[serde(flatten)]
    conversation: ConversationView,
    messages: Vec<MessageView>,
}

#[derive(Serialize)]
pub struct MessageView {
    id: u64,
    /// `user` or `assistant`.
    role: &'static str,
    content: String,
    /// `completed`, `streaming` (being generated now), `failed`, `stopped` or `interrupted`.
    status: &'static str,
    web_search: bool,
    knowledge: bool,
    sources: Vec<Source>,
    kb_sources: Vec<KbSource>,
    tool_count: u32,
    /// Why the answer failed or was interrupted, for the user.
    error: Option<&'static str>,
    created_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RenameRequest {
    title: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SendRequest {
    content: String,
    #[serde(default)]
    web_search: bool,
    /// `None`: search when the guild has documents, as /talk without the option.
    #[serde(default)]
    knowledge: Option<bool>,
}

fn database(_: sqlx::Error) -> ApiError {
    ApiError::Database
}

fn refused(status: StatusCode, code: &'static str, message: impl Into<String>) -> ApiError {
    ApiError::Refused {
        status,
        code,
        message: message.into(),
    }
}

fn busy(busy: Busy) -> ApiError {
    match busy {
        Busy::Key => refused(
            StatusCode::TOO_MANY_REQUESTS,
            "busy",
            "ほかのタブやウィンドウで回答を作成中です。完了するか停止してから送信してください。",
        ),
        Busy::Global => refused(
            StatusCode::TOO_MANY_REQUESTS,
            "server_busy",
            "現在Botが混み合っています。少し待って再試行してください。",
        ),
    }
}

fn guild_param(query: Result<Query<GuildQuery>, QueryRejection>) -> Result<u64, ApiError> {
    query
        .ok()
        .and_then(|Query(query)| query.guild)
        .as_deref()
        .and_then(parse_snowflake)
        .ok_or(ApiError::NotFound)
}

fn conversation_id(value: &str) -> Result<u64, ApiError> {
    parse_snowflake(value).ok_or(ApiError::NotFound)
}

/// Whether the session user may use the bot in `guild` now (Discord's answer is cached for up to
/// 60 seconds; the guild's settings are read every time).
async fn check_use(state: &Web, session: &Session, guild: u64) -> Result<(), ApiError> {
    let resolved = authz::resolve(state, session, guild).await?;
    if !resolved.access.use_bot {
        return Err(refused(StatusCode::FORBIDDEN, "no_use_role", NO_USE_RIGHT));
    }
    Ok(())
}

/// Questions the user sent in the last 24 hours: those stored, or more if this process saw more
/// (conversations deleted since).
async fn daily_used(state: &Web, user: u64) -> Result<u32, ApiError> {
    let since = Utc::now() - chrono::Duration::days(1);
    let stored = state
        .db
        .chat_questions_since(user, since)
        .await
        .map_err(database)?;
    Ok(stored.max(state.chat.recent_questions(user)))
}

fn view(row: &ConversationRow) -> ConversationView {
    ConversationView {
        id: row.id,
        guild_id: row.guild_id,
        title: row.title.clone(),
        created_at: row.created_at,
        updated_at: row.updated_at,
    }
}

/// `running`: the user's answer being generated. Any other `streaming` answer was cut off when
/// its task could not save it, and reads as interrupted.
fn message_view(row: &MessageRow, running: Option<u64>) -> MessageView {
    let status = match row.status {
        Status::Streaming if running != Some(row.id) => Status::Interrupted,
        status => status,
    };
    MessageView {
        id: row.id,
        role: row.role.as_str(),
        content: row.content.clone(),
        status: status.as_str(),
        web_search: row.web_search,
        knowledge: row.knowledge,
        sources: row.sources.clone(),
        kb_sources: row.kb_sources.clone(),
        tool_count: row.tool_count,
        error: failure_message(status, row.error_code.as_deref()),
        created_at: row.created_at,
    }
}

/// The user's explanation of a stored error code (an `AgentError` code, or `timeout` for
/// REQUEST_TIMEOUT_SECONDS).
fn failure_message(status: Status, code: Option<&str>) -> Option<&'static str> {
    match status {
        Status::Failed => Some(match code {
            Some("authentication") => AgentError::Authentication.user_message(),
            Some("rate_limit") => AgentError::RateLimit.user_message(),
            Some("timeout") => AgentError::Timeout.user_message(),
            Some("database") => super::DATABASE_UNAVAILABLE,
            Some("internal") => INTERNAL_ERROR,
            _ => AgentError::Upstream.user_message(),
        }),
        Status::Interrupted => Some(INTERRUPTED),
        _ => None,
    }
}

/// The user's conversations in a guild, with what the composer needs.
pub async fn list(
    State(state): State<AppState>,
    session: Session,
    query: Result<Query<GuildQuery>, QueryRejection>,
) -> Result<Json<ConversationList>, ApiError> {
    let guild = guild_param(query)?;
    check_use(&state, &session, guild).await?;
    let conversations = state
        .db
        .conversations(session.user_id, guild)
        .await
        .map_err(database)?;
    let knowledge = match &state.knowledge {
        Some(knowledge) => knowledge.db.kb_has_ready(guild).await.map_err(database)?,
        None => false,
    };
    Ok(Json(ConversationList {
        conversations: conversations.iter().map(view).collect(),
        knowledge,
        daily_limit: state.config.daily_messages,
        daily_used: daily_used(&state, session.user_id).await?,
    }))
}

/// A conversation to send the first message to: 201 for a new one, 200 when the user's empty
/// conversation in the guild is reused.
pub async fn start(
    State(state): State<AppState>,
    session: Session,
    query: Result<Query<GuildQuery>, QueryRejection>,
) -> Result<(StatusCode, Json<ConversationView>), ApiError> {
    let guild = guild_param(query)?;
    check_use(&state, &session, guild).await?;
    let (row, created) = state
        .db
        .start_conversation(session.user_id, guild, Utc::now())
        .await
        .map_err(database)?;
    if !created {
        return Ok((StatusCode::OK, Json(view(&row))));
    }
    tracing::info!(
        guild_id = guild,
        conversation_id = row.id,
        "web_conversation_created"
    );
    Ok((StatusCode::CREATED, Json(view(&row))))
}

/// A conversation with all its messages.
pub async fn show(
    State(state): State<AppState>,
    session: Session,
    Path(id): Path<String>,
) -> Result<Json<ConversationDetail>, ApiError> {
    let id = conversation_id(&id)?;
    let row = state
        .db
        .conversation(session.user_id, id)
        .await
        .map_err(database)?
        .ok_or(ApiError::NotFound)?;
    let messages = state
        .db
        .conversation_messages(session.user_id, id)
        .await
        .map_err(database)?;
    let running = state.chat.running_answer(session.user_id);
    Ok(Json(ConversationDetail {
        conversation: view(&row),
        messages: messages
            .iter()
            .map(|message| message_view(message, running))
            .collect(),
    }))
}

pub async fn rename(
    State(state): State<AppState>,
    session: Session,
    Path(id): Path<String>,
    JsonBody(request): JsonBody<RenameRequest>,
) -> Result<Json<ConversationView>, ApiError> {
    let id = conversation_id(&id)?;
    let title = valid_title(&request.title).ok_or_else(|| {
        ApiError::Invalid(format!(
            "会話の名前は1〜{MAX_TITLE_CHARS}文字で、改行などの制御文字を含めずに入力してください。"
        ))
    })?;
    if !state
        .db
        .rename_conversation(session.user_id, id, &title)
        .await
        .map_err(database)?
    {
        return Err(ApiError::NotFound);
    }
    let row = state
        .db
        .conversation(session.user_id, id)
        .await
        .map_err(database)?
        .ok_or(ApiError::NotFound)?;
    Ok(Json(view(&row)))
}

/// Deletes a conversation with its messages, stopping its answer if one is being generated.
pub async fn remove(
    State(state): State<AppState>,
    session: Session,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let id = conversation_id(&id)?;
    if !state
        .db
        .delete_conversation(session.user_id, id)
        .await
        .map_err(database)?
    {
        return Err(ApiError::NotFound);
    }
    // Stop only after the rows are gone, so the answer's final save finds nothing and the
    // stream ends silently instead of reporting a `done` for a deleted conversation.
    state.chat.stop_conversation(session.user_id, id);
    tracing::info!(conversation_id = id, "web_conversation_deleted");
    Ok(StatusCode::NO_CONTENT)
}

/// Stops the user's answer being generated; it is saved as `stopped` with its text so far.
pub async fn stop(State(state): State<AppState>, session: Session) -> Json<Value> {
    Json(json!({"stopped": state.chat.stop(session.user_id)}))
}

/// Sends a question and streams the answer as server-sent events: `delta` {text}, `reset` (the
/// text so far was not the answer), `tool` {name, detail}, `kb_sources` {kb_sources},
/// `sources` {sources}, then `done` {message_id, status} or `error` {message}. Refusals before
/// the stream starts are ordinary JSON errors (429 when busy or over the daily limit).
pub async fn send(
    State(state): State<AppState>,
    session: Session,
    Path(id): Path<String>,
    JsonBody(request): JsonBody<SendRequest>,
) -> Result<Sse<impl Stream<Item = Result<Event, Infallible>>>, ApiError> {
    let id = conversation_id(&id)?;
    if request.content.trim().is_empty() || request.content.chars().count() > MAX_QUESTION_CHARS {
        return Err(ApiError::Invalid(
            "メッセージは1〜4,000文字で入力してください。".into(),
        ));
    }
    let user = session.user_id;
    let conversation = state
        .db
        .conversation(user, id)
        .await
        .map_err(database)?
        .ok_or(ApiError::NotFound)?;
    check_use(&state, &session, conversation.guild_id).await?;
    let lease = state.limits.enter(Key::User(user)).map_err(busy)?;
    // Counted under the lease, so two sends of one user cannot both take the last question.
    let limit = state.config.daily_messages;
    if daily_used(&state, user).await? >= limit {
        tracing::info!(conversation_id = id, "web_chat_daily_limit");
        return Err(refused(
            StatusCode::TOO_MANY_REQUESTS,
            "daily_limit",
            format!(
                "直近24時間に送信できるメッセージ（{limit}件）の上限に達しました。時間をおいて再試行してください。"
            ),
        ));
    }
    // Read before the question is stored: everything in the conversation is earlier.
    let turns = context(
        &state
            .db
            .context_messages(user, id, u64::MAX)
            .await
            .map_err(database)?,
    );
    let answer = match state
        .db
        .post_question(&NewTurn {
            user_id: user,
            conversation_id: id,
            content: &request.content,
            web_search: request.web_search,
            knowledge: state.knowledge.is_some() && consult::searches_knowledge(request.knowledge),
            now: Utc::now(),
        })
        .await
        .map_err(database)?
    {
        Posted::Saved { answer, .. } => answer,
        Posted::NotFound => return Err(ApiError::NotFound),
        Posted::Full => {
            return Err(refused(
                StatusCode::CONFLICT,
                "conversation_full",
                format!(
                    "この会話には{MAX_TURNS_PER_CONVERSATION}件までしか送信できません。新しい会話を始めてください。"
                ),
            ));
        }
    };
    state.chat.record_question(user);
    let stop = state.chat.register(user, id, answer);
    let (events, receiver) = mpsc::channel(EVENT_BUFFER);
    tracing::info!(
        conversation_id = id,
        message_id = answer,
        web_search = request.web_search,
        turns = turns.len(),
        "web_chat_started"
    );
    tokio::spawn(generate(
        Job {
            _registration: Registration {
                state: state.clone(),
                user,
                answer,
            },
            state,
            _lease: lease,
            user,
            guild: conversation.guild_id,
            conversation: id,
            answer,
            question: request.content,
            web_search: request.web_search,
            knowledge: request.knowledge,
            turns,
            events,
        },
        stop,
    ));
    Ok(
        Sse::new(ReceiverStream::new(receiver).map(Ok::<_, Infallible>))
            .keep_alive(KeepAlive::new().interval(KEEP_ALIVE)),
    )
}

/// Takes the answer out of the stop registry when its task ends, however it ends.
struct Registration {
    state: AppState,
    user: u64,
    answer: u64,
}

impl Drop for Registration {
    fn drop(&mut self) {
        self.state.chat.unregister(self.user, self.answer);
    }
}

/// One answer being generated. Owns the generation slot until it ends.
struct Job {
    _registration: Registration,
    state: AppState,
    _lease: Lease,
    user: u64,
    guild: u64,
    conversation: u64,
    answer: u64,
    question: String,
    web_search: bool,
    knowledge: Option<bool>,
    turns: Vec<Turn>,
    events: mpsc::Sender<Event>,
}

enum Outcome {
    Completed(Answer),
    Failed {
        code: String,
        message: &'static str,
    },
    /// The stop button.
    Stopped,
    /// The browser went away.
    Gone,
    /// The bot is shutting down.
    Interrupted,
}

/// What a cut-off answer keeps: the text the browser was sent.
#[derive(Default)]
struct Progress {
    text: String,
}

fn sse(name: &'static str, data: Value) -> Event {
    Event::default().event(name).data(data.to_string())
}

/// Sends one of the closing events; a browser that went away or stopped reading is skipped.
async fn deliver(events: &mpsc::Sender<Event>, name: &'static str, data: Value) {
    let _ = tokio::time::timeout(SAVE_TIMEOUT, events.send(sse(name, data))).await;
}

/// Passes an agent event on to the browser, keeping the text it has been sent.
async fn relay(event: StreamEvent, events: &mpsc::Sender<Event>, progress: &mut Progress) {
    let event = match event {
        StreamEvent::Delta(text) => {
            progress.text.push_str(&text);
            sse("delta", json!({"text": text}))
        }
        StreamEvent::Reset => {
            progress.text.clear();
            sse("reset", json!({}))
        }
        StreamEvent::Tool { name, detail } => sse("tool", json!({"name": name, "detail": detail})),
    };
    // A browser that went away is noticed by `generate`.
    let _ = events.send(event).await;
}

/// `stop` is the user's stop button (see `Chat::stop`).
async fn generate(job: Job, mut stop: watch::Receiver<bool>) {
    let started = Instant::now();
    let mut shutdown = job.state.chat.shutdown.subscribe();
    let mut progress = Progress::default();
    let outcome = {
        let work = answer(&job, &mut progress);
        tokio::pin!(work);
        let timeout = tokio::time::sleep(job.state.config.request_timeout);
        tokio::pin!(timeout);
        tokio::select! {
            biased;
            outcome = &mut work => outcome,
            _ = job.events.closed() => Outcome::Gone,
            _ = stop.wait_for(|stop| *stop) => Outcome::Stopped,
            _ = shutdown.wait_for(|stop| *stop) => Outcome::Interrupted,
            () = &mut timeout => Outcome::Failed {
                code: "timeout".into(),
                message: AgentError::Timeout.user_message(),
            },
        }
    };
    let (status, content, sources, tool_count, error_code) = match &outcome {
        Outcome::Completed(answer) => (
            Status::Completed,
            answer.content.as_str(),
            answer.sources.as_slice(),
            answer.tool_count as u32,
            None,
        ),
        Outcome::Failed { code, .. } => (
            Status::Failed,
            progress.text.as_str(),
            &[][..],
            0,
            Some(code.as_str()),
        ),
        Outcome::Stopped | Outcome::Gone => {
            (Status::Stopped, progress.text.as_str(), &[][..], 0, None)
        }
        Outcome::Interrupted => (
            Status::Interrupted,
            progress.text.as_str(),
            &[][..],
            0,
            None,
        ),
    };
    let saved = tokio::time::timeout(
        SAVE_TIMEOUT,
        job.state.db.finish_answer(
            job.user,
            job.answer,
            &Finished {
                status,
                content,
                sources,
                tool_count,
                error_code,
                now: Utc::now(),
            },
        ),
    )
    .await;
    let elapsed_ms = started.elapsed().as_millis() as u64;
    let (conversation_id, message_id) = (job.conversation, job.answer);
    match saved {
        Ok(Ok(true)) => {}
        // The conversation was deleted meanwhile (which also stopped the answer).
        Ok(Ok(false)) => {
            tracing::info!(conversation_id, message_id, "web_chat_discarded");
            return;
        }
        _ => {
            tracing::warn!(conversation_id, message_id, "web_chat_save_failed");
            deliver(&job.events, "error", json!({"message": NOT_SAVED})).await;
            return;
        }
    }
    let status = status.as_str();
    let events = &job.events;
    match &outcome {
        Outcome::Completed(answer) => {
            tracing::info!(
                conversation_id,
                message_id,
                elapsed_ms,
                tool_count,
                status,
                "web_chat_finished"
            );
            if !answer.sources.is_empty() {
                deliver(events, "sources", json!({"sources": answer.sources})).await;
            }
            deliver(
                events,
                "done",
                json!({"message_id": message_id, "status": status}),
            )
            .await;
        }
        Outcome::Failed { code, message } => {
            tracing::warn!(
                conversation_id,
                message_id,
                elapsed_ms,
                error_code = %code,
                "web_chat_failed"
            );
            deliver(events, "error", json!({"message": message})).await;
        }
        Outcome::Stopped | Outcome::Gone => {
            let reason = if matches!(outcome, Outcome::Gone) {
                "disconnected"
            } else {
                "stopped"
            };
            tracing::info!(
                conversation_id,
                message_id,
                elapsed_ms,
                reason,
                status,
                "web_chat_finished"
            );
            deliver(
                events,
                "done",
                json!({"message_id": message_id, "status": status}),
            )
            .await;
        }
        Outcome::Interrupted => {
            tracing::info!(
                conversation_id,
                message_id,
                elapsed_ms,
                status,
                "web_chat_finished"
            );
            deliver(events, "error", json!({"message": INTERRUPTED})).await;
        }
    }
}

/// Consults the knowledge base as /talk does, then streams the answer.
async fn answer(job: &Job, progress: &mut Progress) -> Outcome {
    let state = &job.state;
    let consulted = consult::consult(
        state.knowledge.as_deref(),
        job.guild,
        &job.question,
        job.knowledge,
    )
    .await;
    if let Some(sources) = &consulted.sources {
        if state
            .db
            .record_answer_knowledge(job.user, job.answer, Some(sources))
            .await
            .is_err()
        {
            return Outcome::Failed {
                code: "database".into(),
                message: super::DATABASE_UNAVAILABLE,
            };
        }
        if !sources.is_empty() {
            let _ = job
                .events
                .send(sse("kb_sources", json!({"kb_sources": sources})))
                .await;
        }
    }
    let request = ChatRequest {
        question: &job.question,
        history: &[],
        knowledge: &consulted.excerpts,
        turns: &job.turns,
        web_search: job.web_search,
    };
    let (sender, mut receiver) = mpsc::channel(EVENT_BUFFER);
    let generation = state.agent.respond(&request, Some(&sender));
    tokio::pin!(generation);
    let result = loop {
        tokio::select! {
            biased;
            Some(event) = receiver.recv() => relay(event, &job.events, progress).await,
            result = &mut generation => break result,
        }
    };
    while let Ok(event) = receiver.try_recv() {
        relay(event, &job.events, progress).await;
    }
    match result {
        Ok(mut answer) => {
            if let Some(notice) = consulted.notice {
                answer.content.push_str(notice);
                relay(StreamEvent::Delta(notice.into()), &job.events, progress).await;
            }
            Outcome::Completed(answer)
        }
        Err(error) => Outcome::Failed {
            code: error.to_string(),
            message: error.user_message(),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_stop_registry_follows_the_running_answer() {
        let chat = Chat::default();
        assert!(!chat.stop(1));
        let mut stopped = chat.register(1, 10, 100);
        assert_eq!(chat.running_answer(1), Some(100));
        assert_eq!(chat.running_answer(2), None);
        // Another conversation's delete does not stop it; its own does.
        chat.stop_conversation(1, 11);
        assert!(!*stopped.borrow_and_update());
        chat.stop_conversation(1, 10);
        assert!(*stopped.borrow_and_update());
        assert!(chat.stop(1));
        // A finished answer only removes itself.
        chat.unregister(1, 99);
        assert_eq!(chat.running_answer(1), Some(100));
        chat.unregister(1, 100);
        assert_eq!(chat.running_answer(1), None);
        assert!(!chat.stop(1));

        let mut shutdown = chat.shutdown.subscribe();
        chat.shut_down();
        assert!(*shutdown.borrow_and_update());
    }

    #[test]
    fn recent_questions_are_counted_per_user() {
        let chat = Chat::default();
        assert_eq!(chat.recent_questions(1), 0);
        for _ in 0..3 {
            chat.record_question(1);
        }
        chat.record_question(2);
        assert_eq!(chat.recent_questions(1), 3);
        assert_eq!(chat.recent_questions(2), 1);
        let mut times: VecDeque<Instant> = VecDeque::new();
        if let Some(old) = Instant::now().checked_sub(DAY + Duration::from_secs(1)) {
            times.push_back(old);
            times.push_back(Instant::now());
            forget_old(&mut times);
            assert_eq!(times.len(), 1);
        }
    }

    #[test]
    fn failures_read_as_the_user_explanation() {
        assert_eq!(failure_message(Status::Completed, None), None);
        assert_eq!(failure_message(Status::Stopped, None), None);
        assert_eq!(
            failure_message(Status::Interrupted, None),
            Some(INTERRUPTED)
        );
        assert_eq!(
            failure_message(Status::Failed, Some("rate_limit")),
            Some(AgentError::RateLimit.user_message())
        );
        assert_eq!(
            failure_message(Status::Failed, Some("timeout")),
            Some(AgentError::Timeout.user_message())
        );
        assert_eq!(
            failure_message(Status::Failed, Some("unknown")),
            Some(AgentError::Upstream.user_message())
        );
        let row = MessageRow {
            id: 5,
            role: super::super::chat_store::Role::Assistant,
            content: "途中".into(),
            status: Status::Streaming,
            web_search: false,
            knowledge: false,
            sources: vec![],
            kb_sources: vec![],
            tool_count: 0,
            error_code: None,
            created_at: Utc::now(),
        };
        // Streaming only while its task runs; otherwise it was cut off.
        assert_eq!(message_view(&row, Some(5)).status, "streaming");
        let orphan = message_view(&row, None);
        assert_eq!(orphan.status, "interrupted");
        assert_eq!(orphan.error, Some(INTERRUPTED));
    }
}
